### ISSUE TITLE
No columns displayed for the fishing mortality table

### ISSUE THREAD

**Issue by chantelwetzel-noaa** [chantelwetzel-noaa/wcgfishSAP#10]
Updating the column names in the tables has had the unexpected outcome of the fishing mortality shiny tab not showing any columns. I am unclear about what has caused this issue since I have updated the column names in the ui file.

**Comment by hchiu03** [comment]
Some of the formatting functions for the tables used the old column names, so editing the column names in the server file fixed this issue!
